# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - picissupportchatbotexternal

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: picisregistry.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_FC38B488579F4817ADA0601CB7A73CAE }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_54540DBECCCC4EEFB57A058D5DE8EC47 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: picisregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_FC38B488579F4817ADA0601CB7A73CAE }}/picissupportchatbotexternal:${{ github.sha }}
          file: ./WebApp.Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build

    environment:
      name: External
      url: https://picissupportchatbotexternal.azurewebsites.net/
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_52AEBEAFF53746AFBE99B2098E613636 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_925F327C7ED44FCE8E6E1EE32C7CB705 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DCBB3EBB4F5D47C2A86ED11654965576 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'picissupportchatbotexternal'
          slot-name: 'Production'
          images: 'picisregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_FC38B488579F4817ADA0601CB7A73CAE }}/picissupportchatbotexternal:${{ github.sha }}'
          